# Generated by Django 4.1 on 2022-08-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_forwhom_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffs',
            name='description',
            field=models.TextField(max_length=1500),
        ),
    ]
