# Generated by Django 4.1 on 2022-08-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_aboutme_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
