# Generated by Django 4.1 on 2022-08-23 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_contacts_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, validators=[django.core.validators.RegexValidator(message='Check your email or put another', regex='(^[A-Za-z0-9]+[\\w_]+.[\\w_]+@[0-9A-Za-z]+\\.[a-z]{2,7}$)')])),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone in format xxx xxx xxxx', regex='^((\\+?\\d{3}[- .]?)\\d{7,13}$)')])),
                ('message', models.TextField(blank=True, max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date', '-is_processed'),
            },
        ),
    ]
